version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MODEL_PATH=${MODEL_PATH:-model/ticket_assigner.json}
      - DATA_PATH=${DATA_PATH:-data/issues_mock.csv}

  # Optional: Keep development tools container
  # Uncomment if you want to use a separate container for development
  # dev:
  #   image: node:18-slim
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   working_dir: /app
  #   ports:
  #     - "${DEV_PORT:-3000}:3000"
  #   command: npm run dev